### ISSUE TITLE
Export of Received Rewards

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/WFinfo#12]

**Comment by dapal-003** [comment]
Most asked for format: Clipboard, a condensed format linking the item with square brackets and adding the average value next to each per reward with an indication of the source, be it WFInfo or W.market.

**Comment by TobiTenno** [comment]
something like....
```md
[Forma] 2.5
[Venka Prime Gauntlet] 750
... etc
```

**Comment by dapal-003** [comment]
Implemented with item linking following this format:
"[" + correctName + "]: " + plat + ":platinum:, " + volume + " vol -
