### ISSUE TITLE
Invalid value in Display Time box immediatly crash the app

### ISSUE THREAD

**Issue by tst2005** [WFCD/WFinfo#127]
**Describe the bug**
When you type any value different than digit in the display time setting, the app will immediatly crash.

**To Reproduce**
1. Go to 'Settings'
2. Click on the 'Display Time' box
3. Type something different than a number, like the "a" letter
4. The app will crash immediatly

**Expected behavior**
No crash.
Ignore invalid value (dropping it), only consider digits to get one number.

**Desktop :**
 - OS: W10
 - Version v9.3.1

**Comment by dapal-003** [comment]
Thanks for noting this, sorry for the delay but covid has caused the developers to focus on more important things. It's applied and tested to my development branch if you wish to have an early copy of it. Expected it to be fixed in the next update as well.

**Comment by tst2005** [comment]
It is not a critical/blocking issue. I can wait the next update for the fix.
Thanks a lot for all the work done!

**Comment by dapal-003** [comment]
9.3.2 fixed this issue
