### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by ReverendoGrace** [WFCD/WFinfo#130]
The program fail to launch.
![Uploading Captura de Tela (3).png…]()
[debug.log](https://github.com/WFCD/WFinfo/files/5079825/debug.log)

**Comment by dapal-003** [comment]
`[16/08/2020 01:26:01 9.3.1]   System.TypeInitializationException: O inicializador de tipo de 'WFInfo.OCR' acionou uma exceção. ---> System.Reflection.TargetInvocationException: Uma exceção foi acionada pelo destino de uma chamada. ---> System.DllNotFoundException: Failed to find library "liblept1760.dll" for platform x86.`

It's unable to load in the tesseract dll's. This is a common problem for people that do not have the requirements installed. (c++ 2015-2019) Please refer to [https://github.com/charlesw/tesseract/wiki/Error-2](https://github.com/charlesw/tesseract/wiki/Error-2) for more info
