### ISSUE TITLE
Relics" and "Equipment" sections do not work properly

### ISSUE THREAD

**Issue by Bagny89** [WFCD/WFinfo#133]
**Describe the bug and expected behavior**

Hello everyone, using WFinfo I saw that going in the "Relics" section , all relics do not display platinum items and prices correctly.
While the "Equipment" section displays all the objects as VAULTED, keeping the prices (but we do not know if they are correct).

**Screenshots**

Relics Section
![image](https://user-images.githubusercontent.com/33706352/93457681-9803c200-f8df-11ea-960f-730bdb6defd3.png)

Equipment Section
![image](https://user-images.githubusercontent.com/33706352/93457720-a356ed80-f8df-11ea-8c46-4a5c415db2d9.png)

What does it depend on?

**Desktop :**

OS: Windows 10 Home v2004 build19041.508
WFInfo Version 9.3.1

**Comment by dapal-003** [comment]
Known issue and we're working on it, it's happening due to the fact that DE changed their mobile manifest which means that relics with items no longer show up in the WFCD/warframe-items repository.

**Comment by dapal-003** [comment]
Issue should be resolved, please verify by manually refreshing the data (the reload icons on the left) and restarting the app.

**Comment by dapal-003** [comment]
Marking as closed as there have been no reports on this being an issue anymore
