### ISSUE TITLE
WFInfo crashes on opening

### ISSUE THREAD

**Issue by ComputationalPotato** [WFCD/WFinfo#139]
On running the exe the program will almost immediately crash. I have reinstalled the vc_redist s. Attached is the debug.log
[debug.log](https://github.com/WFCD/WFinfo/files/5580361/debug.log)

**Comment by KintonHiryuu** [comment]
Are you sure both the x64 and the x32 bits vc_redlist are installed, alongside with the .NET framework 4.8 ?

**Comment by ComputationalPotato** [comment]
the .NET framework must have somehow gotten uninstalled since the last time I used WFInfo. Thanks.
