### ISSUE TITLE
Warframe market account issue

### ISSUE THREAD

**Issue by Slashztron** [WFCD/WFinfo#142]
Is there a way to remove my warframe market account info from the application? I tried removing the application and the files that create in the "Appdata - Roaming"
The application still login to the warframe market even after changing the password of the account, which is a bit of a security flaw

**Comment by dapal-003** [comment]
Wfinfo does not save any passwords or e-mails. It relies on storing the JWT token that is supplied from warframe.market. These tokens are valid for up to 60 days after they are generated, this is configured on wfm's end. The token is stored in the registry for security sake. Hence why deleting `%appdata%/wfinfo` did not remove the token. If you wish to manually remove it you can find it over at: `Computer\HKEY_CURRENT_USER\Software\WFinfo`
