### ISSUE TITLE
Button for "Add to Equipment" in Window Mode

### ISSUE THREAD

**Issue by Compegen** [WFCD/WFinfo#144]
**Is your feature request related to a problem? Please describe.**
When doing relic runs I'd like to be able to update my equipment in the app with what I get from the end relic screen without having to do it manually.

**Describe the solution you'd like**
If your running WFInfo in Window mode, there should be an option to select one of the options that was presented & "add" it to your Equipment in the app.

**Comment by dimon222** [comment]
Merged in #263
