### ISSUE TITLE
Equipment: Click checkmark on "owned" item to clear all parts

### ISSUE THREAD

**Issue by Xuerian** [WFCD/WFinfo#146]
**Is your feature request related to a problem? Please describe.**
Accidentally clicking the checkmark in the equipment list means I have to expand then click a bunch of minus buttons to fix it.

**Describe the solution you'd like**
Clear all the parts if I click a fully "owned" equipment item

**Comment by KintonHiryuu** [comment]
Added - @dapal-003 can close
