### ISSUE TITLE
Crash on scroll in relic window (Lith)

### ISSUE THREAD

**Issue by Azuna1** [WFCD/WFinfo#152]
**Describe the bug**
Application crashes when scrolling on relic window

**To Reproduce**
1.  open relic window
2. untick 'hide vaulted'
3. Scroll down to last row
4. app termiantes

**Expected behavior**
not crashing ;)

**Desktop (please complete the following information):**
 - OS: [e.g. W10]
 - .NET version [e.g. 4.8]
 - Version [e.g. v9.3,3]

**Additional context**

>  MyHandler caught : Der Wert darf nicht NULL sein.
> Parametername: element
> [09.02.2021 11:03:09Still in custom entery point]   Runtime terminating: ,True
> [09.02.2021 11:03:09Still in custom entery point]      bei MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
>    bei System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
>    bei System.Windows.Controls.VirtualizingStackPanel.FindScrollOffset(Visual v)
>    bei System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation(Boolean isAnchorOperationPending)
>    bei System.Windows.Controls.VirtualizingStackPanel.OnAnchorOperation()
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
>    bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    bei System.Windows.Threading.DispatcherOperation.Invoke()
>    bei System.Windows.Threading.Dispatcher.ProcessQueue()
>    bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    bei System.Windows.Threadin
>

**Comment by Azuna1** [comment]
#153

**Comment by Azuna1** [comment]
If you expand lith and press "show vaulted" scrolling will crash
If you collapse and expand lith again, its all fine
You can see on the scrollbar that there are probalby alot of null entrys in the TreeNode after clicking Vaulted

**Comment by KintonHiryuu** [comment]
just tried with the new update, fixed for me
