### ISSUE TITLE
Application Hang on Scroll (Axi)

### ISSUE THREAD

**Issue by Azuna1** [WFCD/WFinfo#153]
**Describe the bug**
Application is caught in an endless loop  when reaching bottom of Axis scroll list (with vaueld relics shown)

**To Reproduce**
1. Go to 'relics'
2. untick hide vaulted
2. Click on 'axis'
3. Scroll down to last row

**Expected behavior**
idle cpu and not 100% and flashing unresposive UI

**Desktop (please complete the following information):**
 - OS: [e.g. W10]
 - .NET version [e.g. 4.8]
 - Version [e.g. v9.,3,3]

**Comment by KintonHiryuu** [comment]
WS10 reproducable, but i have no idea what can cause this

**Comment by Azuna1** [comment]
> WS10 reproducable, but i have no idea what can cause this
> note : it only freeze the relics window, not the whole software
> 
> edit : when trying to re-open the window, WFinfo crashes with these logs : https://pastebin.com/adFz2ts7

just run it on the debugger and it should be easy to figure out.
i dont have this thing set up yet nor looked at the code for more than a second :)

**Comment by dimon222** [comment]
Suposedly fixed in #154
