### ISSUE TITLE
Play sound when output is copied to clipboard

### ISSUE THREAD

**Issue by BaileyMillerSSI** [WFCD/WFinfo#155]
**Is your feature request related to a problem? Please describe.**
Because I want to continue using full screen to play the game I have to use the clipboard setting to display the information. Right now I have to wait until almost the last second to paste, read, and figure out which prime part to select. 

**Describe the solution you'd like**
To solve this problem of not knowing when the data has been copied to the clipboard can a sound be played? I wouldn't really care what the sound was and it could even be something that is configured in the setting to be a custom file from my hard drive.

**Comment by dapal-003** [comment]
Wfinfo already has this exact feature. Make sure the display mode is set to "Light" and it will no longer attempt to spawn in a window but rather fill the clipboard and play a sound.

**Comment by BaileyMillerSSI** [comment]
Humm then can I request to customize the sound? I have never heard it before.

**Comment by KintonHiryuu** [comment]
think the sound is hard-coded, but it'll be easy to make it a separate file and let users customize it
