### ISSUE TITLE
Octavia Prime showing up as "Titania Prime" (screenshot)

### ISSUE THREAD

**Issue by GregariousJB** [WFCD/WFinfo#156]
![image](https://i.imgur.com/uNS9hA5.jpeg)

 - OS: W10
 - Version 9.3.3

Probably because Octavia Prime was just released. Just letting someone know. Thanks!

**Comment by dimon222** [comment]
Indeed, it's doing fuzzy matching and it's closest. We will have a look, but most likely it will get autoresolved tonight when Warframe-items picks new mobile API changes.

**Comment by TobiTenno** [comment]
New items _should_ be available to you. She's showing up in [a simple search on the api](https://api.warframestat.us/items/search/octavia%20prime), so should come up ok from y'all's pull.

**Comment by dimon222** [comment]
@GregariousJB do you mind checking out if this issue is still happening now after Octavia is available in our datasets?

**Comment by GregariousJB** [comment]
I didn't test the Octavia Prime Systems like in the screenshot, but I just got the Octavia Prime Neuroptics and it showed up fine in WFinfo. I think this issue is fixed, thanks!
