### ISSUE TITLE
Zephyr Harrier theme support

### ISSUE THREAD

**Issue by MineBill** [WFCD/WFinfo#161]
**Is your feature request related to a problem? Please describe.**
Currently, the Zephyr Harrier UI theme is not supported.

**Describe the solution you'd like**
It would be nice to add support for this theme.

I have no idea what kind of work this requires so i would love to help in any way i can.

**Comment by dapal-003** [comment]
Theme detection/filtering is a tricky one at the moment as there is no real good system set in place to add new themes. 
https://github.com/WFCD/WFinfo/blob/master/WFInfo/Ocr.cs#L56
https://github.com/WFCD/WFinfo/blob/master/WFInfo/Ocr.cs#L71

are where the colors are stored for the theme recognition

https://github.com/WFCD/WFinfo/blob/master/WFInfo/Ocr.cs#L991
This method implements the filtering check

**Comment by KintonHiryuu** [comment]
Added in last update - @dapal-003 can close
