### ISSUE TITLE
Crashed if wrong language

### ISSUE THREAD

**Issue by KintonHiryuu** [WFCD/WFinfo#173]
**Describe the bug**
When the language set in the setting,json file is not recognised by WFinfo, it just make the computer lags very badly, then crashes

**To Reproduce**
1. Change language to something not supported yet (in the settings file a/o using test versions)
2. Start WFinfo current release
3. Crash

Think adding a handler on this to prevent crashing will be great
i'm thinking about  a if language not correct, prompt user then (without modifying settings) fall back to english as default one

*note : i'll work on this later, but i'm more focused on the french part*

**Comment by dapal-003** [comment]
Resolved
