### ISSUE TITLE
Zephyr Prime Blueprint incorrect ducat value

### ISSUE THREAD

**Issue by slinkstr** [WFCD/WFinfo#178]
**Describe the bug**
WFinfo shows Zephyr Prime Blueprint valued at 100 ducats when it is actually 65.

**To Reproduce**
1. Launch WFinfo and download market data
2. Open `%appdata%\WFInfo\market_data.json` and Ctrl+F "Zephyr Prime Blueprint"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET version: 5.0.201
 - Version: WFinfo v9.4.0

**Additional context**
The following all contain correct ducat values:
https://warframe.fandom.com/wiki/Ducats/Prices/All  
https://warframe.market/items/zephyr_prime_blueprint  
https://api.warframe.market/v1/items/zephyr_prime_blueprint  

![Screenshot of incorrect ducat value in GUI](https://i.imgur.com/RpflhI5.png)

**Comment by TobiTenno** [comment]
That one's my bad, most likely. It'll probably update sometime soon? The API that WFInfo pulls data from was on an outdated version of the items db WFInfo uses (warframe-items). It's been updated and should properly work now (or soon).

**Comment by TobiTenno** [comment]
@slinkstr could you verify and let me know if it's still wrong?

**Comment by slinkstr** [comment]
@TobiTenno The values have not updated. https://i.imgur.com/wSBlDnw.png

**Comment by TobiTenno** [comment]
@dimon222 does it still use the API or is it pulling ducats from elsewhere?

**Comment by dimon222** [comment]
@TobiTenno yes it believe it does pull it from same API, but script is running once a day, so it might be either not working properly or happened after script already ran today. Will do a double-check.

**Comment by dapal-003** [comment]
![https://cdn.astolfo.nl/8q4JUb.png](https://cdn.astolfo.nl/8q4JUb.png)
Shows up correctly now
