### ISSUE TITLE
Snap it crash when saving 'Kavasa prime kubrow collar blueprint'

### ISSUE THREAD

**Issue by Chettington** [WFCD/WFinfo#180]
Snap it crashes the app on me when saving 'Kavasa prime kubrow collar blueprint' from my inventory.

Using snap it on the specific item seems to crash it when trying to save the data. All other items in my inventory uploaded correctly but this seems to be the only problem.

**Comment by D1firehail** [comment]
I think I found the cause for this, I'll try to explain what happens. As an example, the inventory data uses "Mesa Prime Systems" for the part, while the scanned item name will be "Mesa Prime Systems Blueprint". The main blueprint is called "Mesa Prime Blueprint" in both places. To decide if " Blueprint" should be cut out, it currently checks if the part after "Prime" is longer than 10 characters ( the length of " Blueprint"), in which case it cuts it out. The part after "Prime" in "Kavasa Prime Kubrow Collar Blueprint" is longer than 10 characters, but it's actually the main blueprint for the item and has the same name in the item database, so it shouldn't actually have " Blueprint" cut out. 

Should be a really simple fix so I'll try to get that sorted tomorrow. While I'm at it I'll take a look at adding some logging to the snap-it item counting system to make problems with it easier to track down.
