### ISSUE TITLE
not running at all

### ISSUE THREAD

**Issue by mamades** [WFCD/WFinfo#184]
there's really not much info I can give it's just not opening 
I can see it running some process on task manager, under details tab, but after 2 seconds it dissappears..

**Comment by TobiTenno** [comment]
seems like you got it working?

**Comment by mamades** [comment]
nope still doesnt work :/ , I just closed the thread because it seems I
must be doing something really wrong

**Comment by dimon222** [comment]
Make sure both parts in point 2 are installed
https://github.com/WFCD/WFinfo#usage

**Comment by dapal-003** [comment]
Sounds to me like you don't have the appropriate runtimes installed. Both the x86 and x64 c++ 2015-2019 redistrubitals need to be present on your machine.

**Comment by mamades** [comment]
They are both installed, cant figure out what goes wrong :S

**Comment by dapal-003** [comment]
If you have a discord account, debugging through on there would be easier. If not, could you send me your debug file located at %appdata%/wfinfo/debug.log to wfinfo@astolfo.nl, and I'll have a look at what causes the program to crash.

**Comment by mamades** [comment]
the debug log is not showing anything :O, its just filled with dashes..
