### ISSUE TITLE
Akjagara Prime Blueprint being read as Gara Prime Blueprint

### ISSUE THREAD

**Issue by Cadwgan** [WFCD/WFinfo#201]
**Describe the bug**
As per the title, OCR is not reading "Akjagara" as one word about 90% of the time.

**To Reproduce**
Use snap it on an Akjagara Prime Blueprint.
Have tried with snap noise values ranging from 0 to 9.

**Screenshots**
![Screenshot 2021-10-09 095354](https://user-images.githubusercontent.com/8039241/136652812-1f1199f9-5256-4473-bf2a-fe156f7cb392.png)
![SnapItImageBounds 2021-10-09 09-39-3452](https://user-images.githubusercontent.com/8039241/136653016-5e3a25a7-e009-47cb-8972-c984fb569b54.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET version 4.8
 - Version v9.4.2

**Comment by D1firehail** [comment]
Fixed in #195 although an update hasn't been pushed out containing that yet

**Comment by D1firehail** [comment]
Also, Snap Noise only affects the number detection part (which will be wrong for the top row regardless in this case, since the top of the snapped area doesn't allign with the top of the item grid)
