### ISSUE TITLE
Connect to Warframe account and download inventory

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/WFinfo#23]
![image](https://user-images.githubusercontent.com/7128721/71787011-bb980e00-2fd7-11ea-9760-b4b5187b0879.png)

**Comment by dimon222** [comment]
DE doesn't disclose user profike APIs. Theatre obtainable if u decompile game files, but can lead to banana and essentially breaking ToS.
However, the existing tesseract parsing mechanism could be theoretically used for parsing inventory windows screen and autofill information for #14

**Comment by TobiTenno** [comment]
that'd be pretty cool

**Comment by dapal-003** [comment]
This has been discuses before, the reality is with the labels in warframe the ability to do so is unreliable at best. I had done some testing back in the day and got low accuracy as the text is smaller and overlaps with the icons more, thus giving more noise.

**Comment by dapal-003** [comment]
Removing due to being unrealistic and cluttering up the issues section
