### ISSUE TITLE
Fullscrean does not work on Win7

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/WFinfo#25]
Status on win8 unknown

![image](https://user-images.githubusercontent.com/7128721/71787043-1f223b80-2fd8-11ea-8b0d-2faaa2e44e14.png)

**Comment by dapal-003** [comment]
Unsure if this is still an issue as of latest version or in the new C# version. Testing of users on win7 is appreciated.

**Comment by davcomNZ** [comment]
Accepted that Win7 will be used for some time yet by a not insignificant number of users but that the window for testing with Win7 users is closing fast. Microsoft EOL cycle stops on Jan 14th 2020 after which no more OS updates from M$. (If you want your free upgrade from Win7 or Win 8/8.1 to Win10 ( using the M$ Media Creation Tool ) then do it before Jan 14th 2020)

**Comment by dapal-003** [comment]
Across the different systems fulllscreen has been causing issues with overlaying. Without getting into drastic measures (Injecting) I don't believe there's a reliable way to overlay on top of full screen. 

With one of the latest (all be it experimental) settings border less fullscreen performance is on-par of full screen. If the user still wants to use fullscreen they can either use the clipboard feature or the window setting.

**Comment by dapal-003** [comment]
Seeing as this problem is out of our hands (Relying on directX injection) we can't solve this without actually messing with the game.
