### ISSUE TITLE
Auto populate Equipment Window

### ISSUE THREAD

**Issue by teoAlivanoglou** [WFCD/WFinfo#253]
**Is your feature request related to a problem? Please describe.**
It's very tedious to look through your inventory and manually pressing the plus button on the Equipment window.

**Describe the solution you'd like**
Since the functionality is already implemented, how about a "mode" where you use Snap It, and you auto populate the Equipment Window?

**Comment by dapal-003** [comment]
It's already implemented under "Master it"

**Comment by D1firehail** [comment]
(worth noting "Master it" is currently broken as I haven't updated it for the UI changes DE made to that screen a while back, and it was never really well documented as nobody has updated the website for ages)

**Comment by D1firehail** [comment]
> It's very tedious to look through your inventory and manually pressing the plus button on the Equipment window.
Oh wait you're not describing Master It, you're describing the Count Items feature that exists as an optional toggle for snap-it

**Comment by teoAlivanoglou** [comment]
My apologies. I didn't realize that's what count it does.
