### ISSUE TITLE
Windows Defender detecting WFInfo as "Trojan:Win32/Bearfoos.A!ml"

### ISSUE THREAD

**Issue by elieux** [WFCD/WFinfo#280]
**Describe the bug**
Defender says the app is a threat.

**To Reproduce**
1. Download wfinfo.zip
2. Wait a bit or try to open it

**Observed behavior**
Defender says wfinfo.exe is a threat called "Trojan:Win32/Bearfoos.A!ml" and blocks it.

**Expected behavior**
Defender lets wfinfo.exe run.

**Screenshots**
![image](https://github.com/WFCD/WFinfo/assets/1399406/27e46446-9459-4b1f-8873-eff678214a9d)

**Desktop:**
 - OS: Windows 11 version 22H2 build 22621.1992
 - Version: 9.6.1

**Additional context**
- Defender security intelligence version: 1.393.1754.0
- Defender security intelligence date: 2023-07-29

**Comment by dimon222** [comment]
WFInfo is relying on external libraries to get it's work done. This is false positive most likely related to Tesseract DLLs  that WFInfo downloads and then loads in-memory. It's a core dependency so there's no plan to ever remove it.
https://github.com/tesseract-ocr/tesseract
