### ISSUE TITLE
"Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder." when running under Lutris on Linux.

### ISSUE THREAD

**Issue by TYTheBeast** [WFCD/WFinfo#336]
**Describe the bug**
The app refuses to open despite Steam and Warframe being open, with Warframe running under Lutris. Running the app through Steam yields the line `ERROR: ld.so: object '/home/thomas/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

**To Reproduce**
1. Go to Lutris
2. Create a new installed local game, configure WFInfo's Wine prefix and other configs.
3. Start WFInfo through Lutris
4. See error through logs

**Expected behavior**
WFInfo should not check for Steam or Warframe, as Steam isn't Warframe's only platform. This dependency is unnecessary and creates complexity.

**Screenshots**
Attempting to open WFInfo through Steam
![image](https://github.com/user-attachments/assets/0af57e4c-170b-4b8d-b566-c6da7b87d738)

Attempt through Lutris:
![image](https://github.com/user-attachments/assets/54b4041f-3535-4728-a36c-8f67c1baa03f)

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - .NET version All of them
 - Version v9.6.5

**Comment by dimon222** [comment]
1. There are no checks for steam in WFInfo code. Literally search in repo if u want.
2. There are checks for Warframe executable OR streaming window of GeForce Now running but purposefully - the app is written around Windows WPF framework and that implies no support of non-Windows OS. Its not .NET Core, but C# WPF specifically. The transition to multi-platform compatibility requires significant rewrite of codebase what is unlikely to happen.
3. You can skip validations of Warframe process by setting "Debug" flag to true in `%APPDATA%/WFinfo/settings.json`.

**Comment by TYTheBeast** [comment]
> 3\. You can skip validations of Warframe process by setting "Debug" flag to true in `%APPDATA%/WFinfo/settings.json`.

Sorry, could you please be more specific? Where does this file need to be? In the working directory? Or in which user? Both my user and steamuser user have the file but nothing's changed.

**Comment by kz-n** [comment]
> 1. There are no checks for steam in WFInfo code. Literally search in repo if u want.
> 
>     2. There are checks for Warframe executable OR streaming window of GeForce Now running but purposefully - the app is written around Windows WPF framework and that implies no support of non-Windows OS. Its not .NET Core, but C# WPF specifically. The transition to multi-platform compatibility requires significant rewrite of codebase what is unlikely to happen.
> 
>     3. You can skip validations of Warframe process by setting "Debug" flag to true in `%APPDATA%/WFinfo/settings.json`.

wine (the compatibility layer between linux and windows) basically is aiming to have the most possible compatiblity with windows, so technically any api of windows should work with wine minus some bugs or features not yet implemented, so in theory you don't need to do anything to support multi-platforms except maybe pinpoint the issue to be reported to wine devs or find a way to make it work with wine, that would make it automatically work for linux and macos users since they can both use the same compatibility tool

**Comment by dimon222** [comment]
> > 3. You can skip validations of Warframe process by setting "Debug" flag to true in `%APPDATA%/WFinfo/settings.json`.
> 
> Sorry, could you please be more specific? Where does this file need to be? In the working directory? Or in which user? Both my user and steamuser user have the file but nothing's changed.

Application data is a special windows specific directory. I have absolutely 0 idea where it resolves under emulated environments like wine/etc like I said as its dependent on how Wine handles such calls.
https://github.com/WFCD/WFinfo/blob/1af2b7558091d012ab502e1f72a90032a2a4250b/WFInfo/Services/TesseractService.cs#L52

> > 1. There are no checks for steam in WFInfo code. Literally search in repo if u want.
> >    
> >    2. There are checks for Warframe executable OR streaming window of GeForce Now running but purposefully - the app is written around Windows WPF framework and that implies no support of non-Windows OS. Its not .NET Core, but C# WPF specifically. The transition to multi-platform compatibility requires significant rewrite of codebase what is unlikely to happen.
> >    3. You can skip validations of Warframe process by setting "Debug" flag to true in `%APPDATA%/WFinfo/settings.json`.
> 
> wine (the compatibility layer between linux and windows) basically is aiming to have the most possible compatiblity with windows, so technically any api of windows should work with wine minus some bugs or features not yet implemented, so in theory you don't need to do anything to support multi-platforms except maybe pinpoint the issue to be reported to wine devs or find a way to make it work with wine, that would make it automatically work for linux and macos users since they can both use the same compatibility tool

Lets be direct, if Wine did its work well, this ticket wouldn't be created. There is no code that forbids running this app outside of Windows OS. What however it has is - it relies on presence of game process to have some functionalities possible (as per change status to Online on Warframe Market to reflect when user is playing the game). User can skip these checks by setting Debug mode on settings file that app creates in special windows user folder. (see link I gave).

Even if you do get app to launch, I have some doubts APIs like checking HDR mode or screenshot functionalities will work properly.

**Comment by dimon222** [comment]
I will close this for now as the answer is basically "wont fix"
However, if you're interested in Linux experience, you can consider checking rewrite on Rust by some community users of WFInfo. It has subset of features, but its better than nothing.
https://github.com/knoellle/wfinfo-ng

**Comment by TYTheBeast** [comment]
Think I'll try contributing to it directly, thank you for the help so far. Happy hunting, Tenno!
