### ISSUE TITLE
Unable to load wiki database any more

### ISSUE THREAD

**Issue by AndrzejDoyle** [WFCD/WFinfo#35]
A few days ago my WFInfo started giving the status "ERROR (ParseScreen)", after which it wouldn't display any overlays.

I was using 8.2.3 at the time, but I've downloaded 8.2.6 and had the same issue, with and without blowing away my AppData directory.

Looking at the [log](https://github.com/WFCD/WFinfo/files/4162442/WFInfo.log) it seems very likely that this is due to edits on the wiki's data dump, when it gets parsed as a Lua script at {Data.vb:603}}.  I've had a quick look through the wiki page's history and nothing jumps out as obviously wrong (timing-wise the two edits on the 31st would seem to be the culprit but they look benign).

I'm also surprised that no-one else seems to be reporting this as it ought to be affecting everyone (after the one-day refresh window).  Perhaps I have a bad NLua DLL being used somehow?

If you can't reproduce this, let me know if there's anything I can do to provide more debugging info.

**Comment by dapal-003** [comment]
It's an error in the Warframe wiki we parse with NLua, however seeing as we've moved over onto a complete re-write of the software (that doesn't use Nlua anymore) we've little to no interest in supporting the older versions. 

[You're able to download the latest beta here, v9.0.](https://github.com/WFCD/WFinfo/releases/tag/v9.0.0-beta) It's core feature is fully functional and even better than the old one. The additional features are currently in the works and are hopefully done before the end of the month.

**Comment by dimon222** [comment]
https://github.com/WFCD/WFinfo/releases/tag/v8.2.7
