### ISSUE TITLE
Auto mode no longer works

### ISSUE THREAD

**Issue by dimon222** [WFCD/WFinfo#5]
Shows reward window with unrelated rewards now
(using Auto mode)

Manually still works properly. It seem to trigger too fast when its Auto even before window itself.

**Comment by dapal-003** [comment]
Auto is known to be buggy, and sadly we can't make it reliable trigger for everyone. With the fact that both lead dev's are no longer actively supporting this repo I can't be certain of the auto future.

**Comment by dimon222** [comment]
Pretty much viable once again in future v9. Closing.
