### ISSUE TITLE
D1 Lith relic table throws exception

### ISSUE THREAD

**Issue by dimon222** [WFCD/WFinfo#6]
![image](https://user-images.githubusercontent.com/2671025/67542246-06cda080-f6ba-11e9-9bc5-1e39cfa2cdb4.png)

Possible that it fails to load gold tier reward.
![image](https://user-images.githubusercontent.com/2671025/67542230-fae1de80-f6b9-11e9-878a-ccdd0049a8f6.png)

**Comment by dapal-003** [comment]
Any references to "Dethcube" currently cause issues with our system, I'm looking into it.

**Comment by dapal-003** [comment]
There was an issue on our backed that didn't properly update, I recommend deleting file market_items.json in %appdata%\WFinfo to update the file to the latest version on the next launch. 
![image](https://user-images.githubusercontent.com/11076306/68534141-3d015600-0331-11ea-8dd7-a2df2a1f8698.png)
