### ISSUE TITLE
Manual theme selection

### ISSUE THREAD

**Issue by dapal-003** [WFCD/WFinfo#60]
Let user choose theme manually in options to automatically preset the OCR configuration. By default choose it to "Auto" and use the pixel based approach like currently do. This should help with some other external overlay popups like for streamers.

**Comment by random-facades** [comment]
Currently there is no need for this features, since all of our OCR detection is done in Warframe Menus, which have the profile bars and menu name text that we use to detect the theme. 

If in the future, we want to do OCR when these items aren't available, then we can readdress this.

**Comment by cristimirt** [comment]
I also think this is needed. For me it fails to detect the Stalker theme correctly, it detects it as Orokin or Vitruvian. And when on Vitruvian, it sometimes detects it as Orokin. 
It also doesn't play well with ReShade, but that's not a big deal. 

If it's not hard to implement, I see no reason not to do it.

**Comment by dapal-003** [comment]
After a lot of back and forth it was decided (as mentioned above) that manually selecting a theme is kind of a hacky way to go about things. 

I would much rather get a debug zip from you and try to work out why it's not working. Stalker has been my go to testing theme, I've never had it fail on me before. You can generate one under options.

As for reshade manual theme selection wouldn't help m, rather you would need a whole custom theme per re-shde user
