### ISSUE TITLE
Discordless error reporting

### ISSUE THREAD

**Issue by dapal-003** [WFCD/WFinfo#61]
Google Forms as option for submitting issue tickets. Allows to fill in main details of issue and helps with some way to organize issues without need of using discord

**Comment by TobiTenno** [comment]
why not just link to here? i can help set up issue templates, if needed

**Comment by dapal-003** [comment]
Of course, that'd be a lot easier. I shouldn't have mentioned that we want to improve the error reporting to be inside of the application. Having a way to do so without account would be preferred

**Comment by TobiTenno** [comment]
ahhh, for sure. I see what you mean.

**Comment by TobiTenno** [comment]
could even set up some sort of web form on your end that receives data from the app where you let them fill out a mini-issue and creates an issue... dunno how that'd go tho.
