### ISSUE TITLE
OCR import

### ISSUE THREAD

**Issue by dapal-003** [WFCD/WFinfo#66]
OCR of whole visible inventory window to identify list of owned stuff

**Comment by dapal-003** [comment]
Requires #14

**Comment by carnufex** [comment]
This should be done asap.

**Comment by dapal-003** [comment]
The current way we track owned items would not be sufficient enough. #14 would need to be completed first.

**Comment by dapal-003** [comment]
Currently it's on indefinite hold due to some limitations:
Snap-it can not interpret numbers, this was deliberate chosen in order to remove false positives with characters like i/l >1 and o > 0

Any string shorter than 2 characters will be dropped to reduce false positives, many of the false positive scans are only one character long, and not a single prime item in the game has a one character long name.  

Item quantity is not necessary for the program to find a reward, due to how snap-it works, the image processing is relative and only that what the user scans. This is done to speed up performance of the already rather slow scanning. This can cause issues with item quantities becoming out of sync
