### ISSUE TITLE
Relic protector

### ISSUE THREAD

**Issue by dapal-003** [WFCD/WFinfo#69]
Identify if relic is vaulted or not in the endless mission screen

**Comment by TobiTenno** [comment]
Could you do something like that for the main relic selection window too? (i guess it's really the same view, isn't it?)

**Comment by dapal-003** [comment]
Relics in the relic screen are already showing they're vaulted/vaulted.

**Comment by TobiTenno** [comment]
In the orbiter? Guess I missed that, sorry.

**Comment by dapal-003** [comment]
Ah, no I was talking about the application itself. Allthough it wouldn't be that difficult seeing as the screens would be the same.

**Comment by EzequielDM** [comment]
I'd like to know if this is planned to come at any point, it would be very useful.

**Comment by KintonHiryuu** [comment]
we did not discussed about it recently, but it may come one day or another

**Comment by PeterJeff** [comment]
Is this considered over relic inventory snap-it simply because the relic selection screen has white background or was there a breakthrough on numerical accuracy?  

Does WFInfo not pre-process the image into binary before OCR stage?

**Comment by dapal-003** [comment]
This idea has been scrapped for a while, just never properly updated on here. Due to how the margin of error on scanning relics is so slim, this feature is not possible. One character being different will cause an entirely different relic being found, currently there is a 1-3 character difference between scan result and found item.
