### ISSUE TITLE
Low Resolutions Missing Parts

### ISSUE THREAD

**Issue by random-facades** [WFCD/WFinfo#72]
When using this low scaling image to simulate lower resolutions, the two right parts get lost..

![50% shot-2](https://user-images.githubusercontent.com/4997353/76140973-17553680-601d-11ea-8bbb-30f561b96598.png)

**Comment by random-facades** [comment]
Issue only occurs with sub-720p resolution/scaling, so marking a low priority

**Comment by dapal-003** [comment]
There will be a point where even humans can't read the text anymore. Where are we going to put the line on the lowest acceptable resolution?

**Comment by dapal-003** [comment]
720p performance is no longer an issue on the right themes, marking as closed.
