### ISSUE TITLE
Akbronco Prime is reported as Vaulted

### ISSUE THREAD

**Issue by dimon222** [WFCD/WFinfo#9]
... when its not.
![image](https://user-images.githubusercontent.com/2671025/71772832-4cabae00-2f20-11ea-8351-8741114a5ce3.png)

**Comment by dapal-003** [comment]
This is an issue with the API we use (warframe.market which is not always up to date) I'll pass this through to them. Thanks.

**Comment by dimon222** [comment]
This is fixed in v9 now since we switched to new source of data where its non-vaulted.
