### ISSUE TITLE
MultiSnapit dimiss key ?

### ISSUE THREAD

**Issue by KintonHiryuu** [WFCD/WFinfo#96]
Dapal - 'I need to ajust the display time of multi snapit'

Possible answer : 
From Zedvia#3786 : 'why dont make it dissapear when you hit the activation key a second time ?'
From me : just add a popup info with options like refresh a/o dimiss, like in this screenshot 
(not a real one ofc, i did some photoshop)
![image](https://user-images.githubusercontent.com/60929021/78034788-78e09a80-7368-11ea-8721-7d33354aa3cf.png)

**Comment by dapal-003** [comment]
Beta for this has been made, please test it out! https://github.com/dapal-003/WFinfo/releases/tag/9.2.3dissmiss

**Comment by dapal-003** [comment]
Implemented https://github.com/WFCD/WFinfo/releases/tag/v9.2.3
